#!/bin/sh

# node already installed

npm install express --save

npm install nodemon --save-dev

npm install body-parser --save
npm install mongodb --save
npm install ejs --save

npm install express-session --save

npm install selenium-webdriver --save
npm install chromedriver --save
npm install mocha chai request --save

# sudo service  nginx restart

cd /var/www/codingexercise/ && npm start
